### ISSUE TITLE
Tests failing: `No module named 'activity_location'`

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#107]
Any idea why the tests are failing? (https://github.com/Urban-Analytics/RAMP-UA/pull/106/checks?check_run_id=996907350) I think it's a problem with package locations:

```
 microsim_model.py:22: in <module>
    from activity_location import ActivityLocation
E   ModuleNotFoundError: No module named 'activity_location'
```

but I can't figure it out. Local tests work OK for me.

**Comment by Sparrow0hawk** [comment]
@nickmalleson this looks like an issue with these relative imports. It should work if we adjust the import lines to
```python
from microsim.activity_location import ActivityLocation
```

I'll write a quick patch that fixes this.

**Comment by Sparrow0hawk** [comment]
@nnelissen within `test_dashboard.py` this line 
https://github.com/Urban-Analytics/RAMP-UA/blob/4f34db1d61c9ef6c8049ef8d654299472c216d2c/tests/test_dashboard.py#L37

Fails for me and the test runner, I think because it will only work if you've run the model once and its created this directory?

I'm not sure how we get around this, unless within this test we call the function that creates this directory?

**Comment by nnelissen** [comment]
@Sparrow0hawk It's only dummy data that shouldn't depend on any previous runs of the model. If it can't find the directory, presumably it can't run any of the following tests since the script assumes the dummy data it reads in next is in that directory. 
Not sure what the best workaround is - have we got some dummy data somewhere I can reuse for this, or do I create the dummy data in the test file (create dataframe instead of reading in pickle file)?

**Comment by Sparrow0hawk** [comment]
@nnelissen is it looking at `dummy_data`? This variable that we're asserting on:

https://github.com/Urban-Analytics/RAMP-UA/blob/4f34db1d61c9ef6c8049ef8d654299472c216d2c/tests/test_dashboard.py#L36

Which creates the following path that the assert fails on:
`/home/medacola/Code/forks/RAMP-UA/devon_data/output/default` as this doesn't seem to be a directory that exists by default in the repo. It derives this from the `default_dashboard.yml`, however the `example_input_params` test fixture looks to use `dummy_data/outputs/` which is a directory that exists by default and so all other tests run and pass.

Is there a function in `dashboard.py` that `test_check_defaults_yml` test is trying to test?

**Comment by nnelissen** [comment]
Sorry, I forgot, you're right! Yes, it was an attempt to test if the default_dashboard.yml input exists (not dummy data), but that would only be the case after the microsim has run and the default_dashboard.yml adjusted accordingly. Maybe we should delete this test here and I can add it as a dashboard error (directory doesn't exist etc)?

**Comment by Sparrow0hawk** [comment]
That's an excellent idea, can always rework the test into a test to check the error is raised within `dashboard.py`

**Comment by nickmalleson** [comment]
I've just rolled this back to fix a problem we found in https://github.com/Urban-Analytics/RAMP-UA/issues/124 @nnelissen and @Sparrow0hawk we may need to re-fix this again as I may have now just re-broken whatever it was you were yrying to fix in https://github.com/Urban-Analytics/RAMP-UA/issues/107; something for when Alex gets back from holiday

**Comment by nickmalleson** [comment]
Nick got it wrong, undid the changes he made in https://github.com/Urban-Analytics/RAMP-UA/commit/b47d471199023ef08fa0e8e25a8a033f83845688 and all is well again
