### ISSUE TITLE
Multiple OpenCL Iterations

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#159]
Adapt the OpenCL notebook (https://github.com/Urban-Analytics/RAMP-UA/blob/master/microsim/analyse_opencl_results.ipynb) so that we can run multiple iterations and generate confidence intervals on the results. I intend to use this as a first step before running some more comprehensive sensitivity testing and later more robust calibration.

**Comment by rory-improbable** [comment]
Hey @nickmalleson I'm not sure exactly what's causing this but I do know that I have had weird problems in the past with python multiprocessing due to the issue that functions you pass need to be picklable (see this [stackoverflow post](https://stackoverflow.com/a/8805244)). This caused weird issues for me where it worked in some contexts but not others, and didn't give useful errors. Unless you have already tried this, it may be worth trying to pickle dump the _run_opencl_model function directly, to see if that works or if it gives you more useful errors, that may be helpful for debugging.

Another thing to consider before spending too long debugging this multiprocessing stuff is that it's worth checking that you actually get a speedup from running multiple instances of the OpenCL model in parallel. Since the idea is that OpenCL already makes use of multithreading to run an individual instance of the model faster than it could on one core, so you might not actually see much further gains by trying to run multiple at once, however these things can be hard to predict in practice so definitely worth giving it a go.

I'll also try and run your notebook myself and see if I can figure out what's going on.

**Comment by rory-improbable** [comment]
So interestingly I just tried this out both from the `temp.py` script and in the jupyter notebook, and it worked in both of them!!

Not really sure what to suggest next. As a sanity check have you tried running the _run_opencl_model() function by itself in the jupyter notebook without multithreading it?

Another thing that can help fix bugs with multiprocessing in python is to use multiple _processes_ rather than multiple threads, which can avoid some of the issues with multithreading. You can do this with concurrent.futures `ProcessPoolExecutor`, see [docs](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor), and also this example [here](https://github.com/BDI-pathogens/OpenABM-Covid19/blob/b7e34d8c18a48d500aa816c71defa7e3b599d101/examples/multi_run_simulator.py#L60) from the Oxford BDI covid19 ABM. 

It could also be some OpenCL weirdness given that OpenCL itself is already doing multithreading for each model execution, but maybe multiple process will help? :man_shrugging:

**Comment by nickmalleson** [comment]
Thanks @rory-improbable , I'll have a look at a `ProcessPoolExecutor`. I think it's probably a weird bug in the jupyter notebook though. Helpfully `itertools` has a `starmap` function as well, which runs in the main process, so I can just use that and otherwise keep the code almost identical if I can't get multiprocessing to work properly. Before I close this, could you just tell me what the output of `conda info jupyter` gives you? The problem may be due to my specific version of the notebook.

```
$ conda list jupyter
# packages in environment at /Users/nick/anaconda3/envs/ramp-ua:
#
# Name                    Version                   Build  Channel
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
```

**Comment by rory-improbable** [comment]
here's my output of `conda list jupyter`, looks identical to yours except I don't have jupyterlab and jupyterlab_server
```
# packages in environment at /home/rory/miniconda3/envs/ramp-ua:
#
# Name                    Version                   Build  Channel
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
```

**Comment by nickmalleson** [comment]
Thanks. It's a weird problem. I'll mess around with my version of jupyter notebook.
