### ISSUE TITLE
Send Python repetition number to R

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#173]
Hi @nickmalleson was wondering if it might be possible to send the repetition value to R from python? Was thinking it might be useful for comparison of scenarios to have paired runs which could be done by setting a seed for each repetition, and was hoping we could use the repetition number as the seed. 

If this would be a total pain/time consuming to do don't bother with it. Had a look to see if I could figure it out but it was beyond my limited python!

**Comment by nickmalleson** [comment]
This is easy @spoonerf . Do you want the number of repetitions (e.g. 50) or the number/ID of the particular model (e.g. 7)

**Comment by spoonerf** [comment]
The number/ID of a particular model would be fantastic!

**Comment by nickmalleson** [comment]
No worries, leave this with me, I can do it today

**Comment by nickmalleson** [comment]
OK fiona I've added the repetition number so that it is passed to the R code. The arguments now passed to R have an aditional integer (`reprn`) before the disease parameters:

https://github.com/Urban-Analytics/RAMP-UA/blob/e0d1975739d1d4d7790592c7278e4348d0d22749/microsim/r_interface.py#L64

Could you update the R code to receive the new parameter? Then it should be good to go. The changes are in branch [nickmalleson-issue-173-Send_Python_repetition_number_to_R](https://github.com/Urban-Analytics/RAMP-UA/tree/nickmalleson-issue-173-Send_Python_repetition_number_to_R)

**Comment by spoonerf** [comment]
Thanks @nickmalleson ! Think it's all good now. Model currently not running all the way through as I made some changes to the R package - should be okay if you merge in #174

**Comment by nickmalleson** [comment]
OK that's merged now, let me know how you get on

**Comment by spoonerf** [comment]
Sorry just realised I could have merged with the branch with the PR! Anyway, all working now, thanks! 

Will update the functions with seed setting but will do that on another branch.

**Comment by nickmalleson** [comment]
All done now I think :-) https://github.com/Urban-Analytics/RAMP-UA/pull/178
