### ISSUE TITLE
Update test data

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#95]
I'm attempting to troubleshoot #79 but have found a discrepancy in the working devon data and dummy data. New devon data appears to include an extra `age` column. 

Could we update the dummy data file [here](https://github.com/Urban-Analytics/RAMP-UA/tree/master/tests/dummy_data/devon-tu_health) to include this column to help me troubleshoot.

I'm not sure how it was created but if its just a simple subsetting operation I'm happy to do it but want to check with @nickmalleson first.

**Comment by nickmalleson** [comment]
@Sparrow0hawk sorry the age columns are confusing. @jabrams23 @spoonerf could you read this too to check this is your understanding too.

In the main data file there are two columns: 'Age1' and 'age'. 'Age1' contains the individual ages of the people and was added recently when we read the new data from Karyn. 'age' is an age group (1-6). @jabrams23 @spoonerf do you actually use the 'age' column? If not, I will stop adding it to the individuals data file that is sent to R.

I know it would be better to rename the columns for clarity, but I don't think we should as the new data files that Karyn is producing for the UK will probably have the same names.

@Sparrow0hawk in (https://github.com/Urban-Analytics/RAMP-UA/commit/3385df88c6c1fae2557b06a7bacccbf07f8550e5) I have just added a new column in the dummy data called 'age' so that it is consistent with main data (as it's a csv file I just did it in excel, but I'm sure a nice combination of `cut` and `grep` or whatever would have been much more elegant :-) I also changed the data themselves so that in the dummy file 'age' is now age group (1-6) and 'Age1' has raw ages, but unless you are doing some analysis based on the ages themselves this wont affect any of the tests.

**Comment by nickmalleson** [comment]
(I merged the changes in https://github.com/Urban-Analytics/RAMP-UA/pull/96 )

**Comment by spoonerf** [comment]
Hi @nickmalleson I think it is the other way around so that 'age' is the continuous column and 'Age1' is the 1-6. It looks like that is still the case in the latest data? 

We use the 'age' (continuous age) column to apply the age base survival rates and I believe @nnelissen uses the 'Age1' (1-6) column to do some visualisation of cases across age groups.

**Comment by nickmalleson** [comment]
Oh crap you're right,  I think that means my primary/secondary allocation is wrong. I'll fix that now and  also swap the columns round in the dummy data. I'm glad I checked with you!!

**Comment by nickmalleson** [comment]
> Oh crap you're right, I think that means my primary/secondary allocation is wrong. I'll fix that now and also swap the columns round in the dummy data. I'm glad I checked with you!!

fixed in https://github.com/Urban-Analytics/RAMP-UA/pull/97
